container:
  image: golang:latest

task:
  container:
    image: golangci/golangci-lint:latest
  name: Lint
  script: golangci-lint run -v --out-format json -p bugs,complexity,format,performance,style,unused -D goimports,wsl,gochecknoglobals,funlen,noctx,gofumpt > golangci.json
  always:
    artifacts:
      path: golangci.json
      type: text/json
      format: golangci

docker_builder:
  name: Test
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.14.6.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test -v -p 1 ./...
  env:
    HOME: /root

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: goreleaser/goreleaser:latest
  release_script: goreleaser
