docker_builder:
  name: Test (Linux with Docker)
  alias: Tests
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.17.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root

docker_builder:
  name: Test (Linux with Podman)
  allow_failures: true
  alias: Tests
  install_podman_script:
    - sudo apt-get -y install podman
  configure_podman_script:
    - echo 'unqualified-search-registries=["docker.io"]' > /etc/containers/registries.conf.d/docker.conf
  work_around_gcloud_credential_helper_script:
    - rm /root/.docker/config.json
  run_podman_background_script:
    - podman system service -t 0 unix:///tmp/podman.sock
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.17.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root
    CIRRUS_CONTAINER_BACKEND: podman

docker_builder:
  name: Test (Windows)
  alias: Tests
  platform: windows
  os_version: 2019
  test_script:
    - choco install -y golang git
    - refreshenv
    - md C:\Windows\system32\config\systemprofile\AppData\Local\Temp
    - go test -v ./...

task:
  name: Test (macOS with Docker and Parallels)
  alias: Tests
  persistent_worker:
    labels:
      os: darwin
      parallels: installed
  env:
    CIRRUS_INTERNAL_PARALLELS_DARWIN_VM: monterey-base
    CIRRUS_INTERNAL_PARALLELS_DARWIN_SSH_USER: admin
    CIRRUS_INTERNAL_PARALLELS_DARWIN_SSH_PASSWORD: admin
    CIRRUS_INTERNAL_PARALLELS_LINUX_VM: debian
    CIRRUS_INTERNAL_PARALLELS_LINUX_SSH_USER: parallels
    CIRRUS_INTERNAL_PARALLELS_LINUX_SSH_PASSWORD: parallels
    CIRRUS_INTERNAL_NO_GITHUB_API_TESTS: yes
  test_script:
    - go test -p 1 ./...

task:
  name: Release (Dry Run)
  only_if: $CIRRUS_TAG == ''
  container:
    image: golang:latest
    cpu: 4
    memory: 12G
  install_script:
    - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
    - apt-get update
    - apt-get -y install goreleaser
  release_script: goreleaser build --snapshot
  binaries_artifacts:
    path: "dist/cirrus_*/cirrus*"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Tests
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: golang:latest
    cpu: 4
    memory: 12G
  install_script:
    - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
    - apt-get update
    - apt-get -y install goreleaser
  release_script: goreleaser
