docker_builder:
  name: Test (Docker)
  alias: Tests
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.15.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root

docker_builder:
  name: Test (Podman)
  alias: Tests
  install_podman_script:
    - . /etc/os-release
    - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get -y upgrade
    - sudo apt-get -y install podman
  run_podman_background_script:
    - podman system service -t 0 unix:///tmp/podman.sock
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.15.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root
    CIRRUS_CONTAINER_BACKEND: podman

task:
  name: Release (Dry Run)
  only_if: $CIRRUS_PR != ''
  depends_on:
    - Lint
    - Tests
  container:
    image: goreleaser/goreleaser:latest
  release_script: goreleaser build --snapshot
  binaries_artifacts:
    path: "dist/cirrus_*/cirrus*"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: goreleaser/goreleaser:latest
  release_script: goreleaser
