container:
  image: golang:latest

task:
  container:
    image: golangci/golangci-lint:latest
  name: Lint
  script: golangci-lint run -v --out-format json -p bugs,complexity,format,performance,style,unused -D goimports,wsl,gochecknoglobals,funlen,noctx,gofumpt > golangci.json
  always:
    artifacts:
      path: golangci.json
      type: text/json
      format: golangci

task:
  name: Test
  script: go test -v ./...

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  container:
    image: goreleaser/goreleaser:latest
  release_script: gorelease
