docker_builder:
  name: Test (Linux with Docker)
  alias: Tests
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.15.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root

docker_builder:
  name: Test (Linux with Podman)
  alias: Tests
  install_podman_script:
    - sudo rm /root/.docker/config.json || true
    - . /etc/os-release
    - echo "deb https://ftp.gwdg.de/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    - curl -L https://ftp.gwdg.de/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get -y upgrade
    - sudo apt-get -y install podman
  run_podman_background_script:
    - podman system service -t 0 unix:///tmp/podman.sock
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.15.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root
    CIRRUS_CONTAINER_BACKEND: podman

docker_builder:
  name: Test (Windows)
  alias: Tests
  platform: windows
  os_version: 2019
  test_script:
    - choco install -y golang
    - refreshenv
    - md C:\Windows\system32\config\systemprofile\AppData\Local\Temp
    - go test ./...

task:
  name: Test (macOS with Docker and Parallels)
  alias: Tests
  persistent_worker:
    labels:
      os: darwin
      docker: installed
      parallels: installed
  env:
    CIRRUS_INTERNAL_PARALLELS_VM: big-sur-base
    CIRRUS_INTERNAL_PARALLELS_SSH_USER: admin
    CIRRUS_INTERNAL_PARALLELS_SSH_PASSWORD: admin
  test_script:
    - go version
    - go test -p 1 ./...

task:
  name: Release (Dry Run)
  only_if: $CIRRUS_TAG == ''
  container:
    image: golang:latest
    cpu: 4
    memory: 12G
  install_script: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  release_script: ./bin/goreleaser build --snapshot
  binaries_artifacts:
    path: "dist/cirrus_*/cirrus*"

apple_silicon: &APPLE_SILICON_BUILD
  osx_instance:
    image: catalina-xcode
  env:
    GOPATH: $HOME/go
    PATH: $GOPATH/bin:$PATH
  install_script:
    - brew update
    - brew install go
  gotip_script:
    - go get golang.org/dl/gotip
    - gotip download
    - gotip version
  build_script:
    - CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 gotip build -o cirrus-darwin-arm64 -ldflags "-X github.com/cirruslabs/cirrus-cli/internal/version.Version=$CIRRUS_TAG" cmd/cirrus/main.go

task:
  name: Release Apple Silicon (Dry Run)
  only_if: $CIRRUS_TAG == ''
  << : *APPLE_SILICON_BUILD
  binary_artifacts:
    path: cirrus-darwin-arm64

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Tests
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: golang:latest
    cpu: 4
    memory: 12G
  install_script: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  release_script: ./bin/goreleaser

task:
  name: Release Apple Silicon
  only_if: $CIRRUS_RELEASE != ''
  depends_on: Release
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  <<: *APPLE_SILICON_BUILD
  upload_script: |
    curl -X POST \
        --data-binary @cirrus-darwin-arm64 \
        --header "Authorization: token $GITHUB_TOKEN" \
        --header "Content-Type: application/octet-stream" \
        https://uploads.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/$CIRRUS_RELEASE/assets?name=cirrus-darwin-arm64
