task:
  name: Test EBS
  aws_credentials:
    role_arn: arn:aws:iam::944424729675:role/VetuIntegrationTests
    role_session_name: cirrus
    region: us-east-2
  ec2_instance:
    image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*
    region: us-east-2
    type: t2.medium
    block_device_mappings:
      - device_name: /dev/xvda
        ebs:
          volume_size: 100
  dh_script: df -h
  lsblk1_script: lsblk
  resize_script: sudo resize2fs /dev/xvda1
  lsblk2_script: lsblk
