container:
  image: golang:latest

task:
  container:
    image: golangci/golangci-lint:latest
  name: Lint
  script: golangci-lint run -v --out-format json -p bugs,complexity,format,performance,style,unused -D goimports,wsl,gochecknoglobals,funlen,noctx,gofumpt > golangci.json
  always:
    artifacts:
      path: golangci.json
      type: text/json
      format: golangci

task:
  name: Test
  script: go test -v ./...

task:
  name: Build and Publish
  depends_on:
    - Lint
    - Test
  script:
    - wget -O - https://github.com/goreleaser/goreleaser/releases/download/v0.140.0/goreleaser_Linux_x86_64.tar.gz | tar xz goreleaser
    - ./goreleaser
