task:
  name: Test EBS
  aws_credentials:
    role_arn: arn:aws:iam::944424729675:role/VetuIntegrationTests
    role_session_name: cirrus
    region: us-east-2
  ec2_instance:
    image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-*
    architecture: arm64
    region: us-east-2
    type: a1.metal
    block_device_mappings:
      - device_name: /dev/xvda
        ebs:
          volume_size: 100
  dh_script: df -h
  lsblk_script: lsblk
