task:
  use_compute_credits: true
  name: Test (Windows)
  alias: Tests
  compute_engine_instance:
    image_project: windows-cloud
    image: family/windows-2022-core
    platform: windows
  enable_windows_containers_script:
    - ps: Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1" -o install-docker-ce.ps1
    - ps: .\install-docker-ce.ps1
  install_chocolatey_script:
    - ps: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  test_script:
    - choco install -y golang git
    - refreshenv
    - md C:\Windows\system32\config\systemprofile\AppData\Local\Temp
    - go test -v ./...
