project_name: cirrus

before:
  hooks:
    - go mod download

builds:
  - main: cmd/cirrus/main.go
    ldflags: "-X github.com/cirruslabs/cirrus-cli/internal/commands.version={{.Version}}-{{.ShortCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
