project_name: cirrus

before:
  hooks:
    - go mod download

builds:
  - main: cmd/cirrus/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

brews:
  -
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/cirrus-cli
    description: CLI for running Cirrus Tasks locally in Docker containers

