project_name: cirrus

before:
  hooks:
    - go mod download

builds:
  - main: cmd/cirrus/main.go
    ldflags: "-X github.com/cirruslabs/cirrus-cli/internal/commands.version={{.Version}}-{{.ShortCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: cirrus
    ids:
      - regular
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/cirrus-cli
    description: CLI for running Cirrus Tasks locally in Docker containers
    skip_upload: auto
