project_name: cirrus

before:
  hooks:
    - go mod download

builds:
  - main: cmd/cirrus/main.go
    ldflags: >
      -X github.com/cirruslabs/cirrus-cli/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/cirrus-cli/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED={{if eq .Os "darwin"}}1{{else}}0{{end}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
    hooks:
      post:
        - bash .ci/remove-signature.sh {{ .Path }}

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: cirrus
    ids:
      - regular
    repository:
      owner: cirruslabs
      name: homebrew-cli
    license: AGPL-3.0-only
    install: |
      bin.install "cirrus"
      generate_completions_from_executable(bin/"cirrus", "completion")
    caveats: See the Github repository for more information

nfpms:
  - package_name: cirrus-cli
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/cirrus-cli
    maintainer: support@cirruslabs.org
    description: CLI for executing Cirrus tasks locally and in any CI
    license: AGPL-3.0-only
    section: devel
    formats:
      - deb
      - rpm

furies:
  - account: cirruslabs

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
