/*
 * Provides a container compatible interface.
 *
 * This documentation describes the Podman v2.0 RESTful API. It replaces the Podman v1.0 API and was initially delivered along with Podman v2.0.  It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /var/run/docker.sock to /run/podman/podman.sock  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v1.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v1.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v1.0.0/libpod/images/json' | jq
 *
 * API version: 0.0.1
 * Contact: podman@lists.podman.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// InspectMount provides a record of a single mount in a container. It contains fields for both named and normal volumes. Only user-specified volumes will be included, and tmpfs volumes are not included even if the user specified them.
type InspectMount struct {
	// The destination directory for the volume. Specified as a path within the container, as it would be passed into the OCI runtime.
	Destination string `json:"Destination,omitempty"`
	// The driver used for the named volume. Empty for bind mounts.
	Driver string `json:"Driver,omitempty"`
	// Contains SELinux :z/:Z mount options. Unclear what, if anything, else goes in here.
	Mode string `json:"Mode,omitempty"`
	// The name of the volume. Empty for bind mounts.
	Name string `json:"Name,omitempty"`
	// All remaining mount options. Additional data, not present in the original output.
	Options []string `json:"Options,omitempty"`
	// Mount propagation for the mount. Can be empty if not specified, but is always printed - no omitempty.
	Propagation string `json:"Propagation,omitempty"`
	// Whether the volume is read-write
	RW bool `json:"RW,omitempty"`
	// The source directory for the volume.
	Source string `json:"Source,omitempty"`
	// Whether the mount is a volume or bind mount. Allowed values are \"volume\" and \"bind\".
	Type_ string `json:"Type,omitempty"`
}
