/*
 * Provides a container compatible interface.
 *
 * This documentation describes the Podman v2.0 RESTful API. It replaces the Podman v1.0 API and was initially delivered along with Podman v2.0.  It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /var/run/docker.sock to /run/podman/podman.sock  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v1.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v1.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v1.0.0/libpod/images/json' | jq
 *
 * API version: 0.0.1
 * Contact: podman@lists.podman.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SpecGenerator creates an OCI spec and Libpod configuration options to create a container based on the given configuration.
type SpecGenerator struct {
	// Annotations are key-value options passed into the container runtime that can be used to trigger special behavior. Optional.
	Annotations map[string]string `json:"annotations,omitempty"`
	// ApparmorProfile is the name of the Apparmor profile the container will use. Optional.
	ApparmorProfile string `json:"apparmor_profile,omitempty"`
	// CapAdd are capabilities which will be added to the container. Conflicts with Privileged. Optional.
	CapAdd []string `json:"cap_add,omitempty"`
	// CapDrop are capabilities which will be removed from the container. Conflicts with Privileged. Optional.
	CapDrop []string `json:"cap_drop,omitempty"`
	// CgroupParent is the container's CGroup parent. If not set, the default for the current cgroup driver will be used. Optional.
	CgroupParent string `json:"cgroup_parent,omitempty"`
	Cgroupns *Namespace `json:"cgroupns,omitempty"`
	// CgroupsMode sets a policy for how cgroups will be created in the container, including the ability to disable creation entirely.
	CgroupsMode string `json:"cgroups_mode,omitempty"`
	// CNINetworks is a list of CNI networks to join the container to. If this list is empty, the default CNI network will be joined instead. If at least one entry is present, we will not join the default network (unless it is part of this list). Only available if NetNS is set to bridge. Optional.
	CniNetworks []string `json:"cni_networks,omitempty"`
	// Command is the container's command. If not given and Image is specified, this will be populated by the image's configuration. Optional.
	Command []string `json:"command,omitempty"`
	// ConmonPidFile is a path at which a PID file for Conmon will be placed. If not given, a default location will be used. Optional.
	ConmonPidFile string `json:"conmon_pid_file,omitempty"`
	// ContainerCreateCommand is the command that was used to create this container. This will be shown in the output of Inspect() on the container, and may also be used by some tools that wish to recreate the container (e.g. `podman generate systemd --new`). Optional.
	ContainerCreateCommand []string `json:"containerCreateCommand,omitempty"`
	// Devices are devices that will be added to the container. Optional.
	Devices []LinuxDevice `json:"devices,omitempty"`
	// DNSOptions is a set of DNS options that will be used in the container's resolv.conf, replacing the host's DNS options which are used by default. Conflicts with UseImageResolvConf. Optional.
	DnsOption []string `json:"dns_option,omitempty"`
	// DNSSearch is a set of DNS search domains that will be used in the container's resolv.conf, replacing the host's DNS search domains which are used by default. Conflicts with UseImageResolvConf. Optional.
	DnsSearch []string `json:"dns_search,omitempty"`
	// DNSServers is a set of DNS servers that will be used in the container's resolv.conf, replacing the host's DNS Servers which are used by default. Conflicts with UseImageResolvConf. Optional.
	DnsServer [][]int32 `json:"dns_server,omitempty"`
	// Entrypoint is the container's entrypoint. If not given and Image is specified, this will be populated by the image's configuration. Optional.
	Entrypoint []string `json:"entrypoint,omitempty"`
	// Env is a set of environment variables that will be set in the container. Optional.
	Env map[string]string `json:"env,omitempty"`
	// EnvHost indicates that the host environment should be added to container Optional.
	EnvHost bool `json:"env_host,omitempty"`
	// Expose is a number of ports that will be forwarded to the container if PublishExposedPorts is set. Expose is a map of uint16 (port number) to a string representing protocol. Allowed protocols are \"tcp\", \"udp\", and \"sctp\", or some combination of the three separated by commas. If protocol is set to \"\" we will assume TCP. Only available if NetNS is set to Bridge or Slirp, and PublishExposedPorts is set. Optional.
	Expose *interface{} `json:"expose,omitempty"`
	// Groups are a list of supplemental groups the container's user will be granted access to. Optional.
	Groups []string `json:"groups,omitempty"`
	Healthconfig *Schema2HealthConfig `json:"healthconfig,omitempty"`
	// HostAdd is a set of hosts which will be added to the container's etc/hosts file. Conflicts with UseImageHosts. Optional.
	Hostadd []string `json:"hostadd,omitempty"`
	// Hostname is the container's hostname. If not set, the hostname will not be modified (if UtsNS is not private) or will be set to the container ID (if UtsNS is private). Conflicts with UtsNS if UtsNS is not set to private. Optional.
	Hostname string `json:"hostname,omitempty"`
	// EnvHTTPProxy indicates that the http host proxy environment variables should be added to container Optional.
	Httpproxy bool `json:"httpproxy,omitempty"`
	Idmappings *IdMappingOptions `json:"idmappings,omitempty"`
	// Image is the image the container will be based on. The image will be used as the container's root filesystem, and its environment vars, volumes, and other configuration will be applied to the container. Conflicts with Rootfs. At least one of Image or Rootfs must be specified.
	Image string `json:"image,omitempty"`
	// ImageVolumeMode indicates how image volumes will be created. Supported modes are \"ignore\" (do not create), \"tmpfs\" (create as tmpfs), and \"anonymous\" (create as anonymous volumes). The default if unset is anonymous. Optional.
	ImageVolumeMode string `json:"image_volume_mode,omitempty"`
	// Init specifies that an init binary will be mounted into the container, and will be used as PID1.
	Init bool `json:"init,omitempty"`
	// InitPath specifies the path to the init binary that will be added if Init is specified above. If not specified, the default set in the Libpod config will be used. Ignored if Init above is not set. Optional.
	InitPath string `json:"init_path,omitempty"`
	Ipcns *Namespace `json:"ipcns,omitempty"`
	// Labels are key-value pairs that are used to add metadata to containers. Optional.
	Labels map[string]string `json:"labels,omitempty"`
	LogConfiguration *LogConfig `json:"log_configuration,omitempty"`
	// Mounts are mounts that will be added to the container. These will supersede Image Volumes and VolumesFrom volumes where there are conflicts. Optional.
	Mounts []Mount `json:"mounts,omitempty"`
	// Name is the name the container will be given. If no name is provided, one will be randomly generated. Optional.
	Name string `json:"name,omitempty"`
	// Namespace is the libpod namespace the container will be placed in. Optional.
	Namespace string `json:"namespace,omitempty"`
	Netns *Namespace `json:"netns,omitempty"`
	// NetworkOptions are additional options for each network Optional.
	NetworkOptions map[string][]string `json:"network_options,omitempty"`
	// NoNewPrivileges is whether the container will set the no new privileges flag on create, which disables gaining additional privileges (e.g. via setuid) in the container.
	NoNewPrivileges bool `json:"no_new_privileges,omitempty"`
	// OCIRuntime is the name of the OCI runtime that will be used to create the container. If not specified, the default will be used. Optional.
	OciRuntime string `json:"oci_runtime,omitempty"`
	// OOMScoreAdj adjusts the score used by the OOM killer to determine processes to kill for the container's process. Optional.
	OomScoreAdj int64 `json:"oom_score_adj,omitempty"`
	// Overlay volumes are named volumes that will be added to the container. Optional.
	OverlayVolumes []OverlayVolume `json:"overlay_volumes,omitempty"`
	Pidns *Namespace `json:"pidns,omitempty"`
	// Pod is the ID of the pod the container will join. Optional.
	Pod string `json:"pod,omitempty"`
	// PortBindings is a set of ports to map into the container. Only available if NetNS is set to bridge or slirp. Optional.
	Portmappings []PortMapping `json:"portmappings,omitempty"`
	// Privileged is whether the container is privileged. Privileged does the following: Adds all devices on the system to the container. Adds all capabilities to the container. Disables Seccomp, SELinux, and Apparmor confinement. (Though SELinux can be manually re-enabled). TODO: this conflicts with things. TODO: this does more.
	Privileged bool `json:"privileged,omitempty"`
	// ProcOpts are the options used for the proc mount.
	ProcfsOpts []string `json:"procfs_opts,omitempty"`
	// PublishExposedPorts will publish ports specified in the image to random unused ports (guaranteed to be above 1024) on the host. This is based on ports set in Expose below, and any ports specified by the Image (if one is given). Only available if NetNS is set to Bridge or Slirp.
	PublishImagePorts bool `json:"publish_image_ports,omitempty"`
	// Rlimits are POSIX rlimits to apply to the container. Optional.
	RLimits []PosixRlimit `json:"r_limits,omitempty"`
	// RawImageName is the user-specified and unprocessed input referring to a local or a remote image.
	RawImageName string `json:"raw_image_name,omitempty"`
	// ReadOnlyFilesystem indicates that everything will be mounted as read-only
	ReadOnlyFilesystem bool `json:"read_only_filesystem,omitempty"`
	// Remove indicates if the container should be removed once it has been started and exits
	Remove bool `json:"remove,omitempty"`
	ResourceLimits *LinuxResources `json:"resource_limits,omitempty"`
	// RestartPolicy is the container's restart policy - an action which will be taken when the container exits. If not given, the default policy, which does nothing, will be used. Optional.
	RestartPolicy string `json:"restart_policy,omitempty"`
	// RestartRetries is the number of attempts that will be made to restart the container. Only available when RestartPolicy is set to \"on-failure\". Optional.
	RestartTries int32 `json:"restart_tries,omitempty"`
	// Rootfs is the path to a directory that will be used as the container's root filesystem. No modification will be made to the directory, it will be directly mounted into the container as root. Conflicts with Image. At least one of Image or Rootfs must be specified.
	Rootfs string `json:"rootfs,omitempty"`
	// RootfsPropagation is the rootfs propagation mode for the container. If not set, the default of rslave will be used. Optional.
	RootfsPropagation string `json:"rootfs_propagation,omitempty"`
	// Determine how to handle the NOTIFY_SOCKET - do we participate or pass it through \"container\" - let the OCI runtime deal with it, advertise conmon's MAINPID \"conmon-only\" - advertise conmon's MAINPID, send READY when started, don't pass to OCI \"ignore\" - unset NOTIFY_SOCKET
	SdnotifyMode string `json:"sdnotifyMode,omitempty"`
	// SeccompPolicy determines which seccomp profile gets applied the container. valid values: empty,default,image
	SeccompPolicy string `json:"seccomp_policy,omitempty"`
	// SeccompProfilePath is the path to a JSON file containing the container's Seccomp profile. If not specified, no Seccomp profile will be used. Optional.
	SeccompProfilePath string `json:"seccomp_profile_path,omitempty"`
	// SelinuxProcessLabel is the process label the container will use. If SELinux is enabled and this is not specified, a label will be automatically generated if not specified. Optional.
	SelinuxOpts []string `json:"selinux_opts,omitempty"`
	// ShmSize is the size of the tmpfs to mount in at /dev/shm, in bytes. Conflicts with ShmSize if IpcNS is not private. Optional.
	ShmSize int64 `json:"shm_size,omitempty"`
	StaticIp *[]int32 `json:"static_ip,omitempty"`
	StaticIpv6 *[]int32 `json:"static_ipv6,omitempty"`
	StaticMac *[]int32 `json:"static_mac,omitempty"`
	// Stdin is whether the container will keep its STDIN open.
	Stdin bool `json:"stdin,omitempty"`
	StopSignal int64 `json:"stop_signal,omitempty"`
	// StopTimeout is a timeout between the container's stop signal being sent and SIGKILL being sent. If not provided, the default will be used. If 0 is used, stop signal will not be sent, and SIGKILL will be sent instead. Optional.
	StopTimeout int32 `json:"stop_timeout,omitempty"`
	// Sysctl sets kernel parameters for the container
	Sysctl map[string]string `json:"sysctl,omitempty"`
	// Systemd is whether the container will be started in systemd mode. Valid options are \"true\", \"false\", and \"always\". \"true\" enables this mode only if the binary run in the container is sbin/init or systemd. \"always\" unconditionally enables systemd mode. \"false\" unconditionally disables systemd mode. If enabled, mounts and stop signal will be modified. If set to \"always\" or set to \"true\" and conditionally triggered, conflicts with StopSignal. If not specified, \"false\" will be assumed. Optional.
	Systemd string `json:"systemd,omitempty"`
	// Terminal is whether the container will create a PTY. Optional.
	Terminal bool `json:"terminal,omitempty"`
	// IO read rate limit per cgroup per device, bytes per second
	ThrottleReadBpsDevice map[string]LinuxThrottleDevice `json:"throttleReadBpsDevice,omitempty"`
	// IO read rate limit per cgroup per device, IO per second
	ThrottleReadIOPSDevice map[string]LinuxThrottleDevice `json:"throttleReadIOPSDevice,omitempty"`
	// IO write rate limit per cgroup per device, bytes per second
	ThrottleWriteBpsDevice map[string]LinuxThrottleDevice `json:"throttleWriteBpsDevice,omitempty"`
	// IO write rate limit per cgroup per device, IO per second
	ThrottleWriteIOPSDevice map[string]LinuxThrottleDevice `json:"throttleWriteIOPSDevice,omitempty"`
	// Timezone is the timezone inside the container. Local means it has the same timezone as the host machine
	Timezone string `json:"timezone,omitempty"`
	// Umask is the umask the init process of the container will be run with.
	Umask string `json:"umask,omitempty"`
	// CgroupConf are key-value options passed into the container runtime that are used to configure cgroup v2. Optional.
	Unified map[string]string `json:"unified,omitempty"`
	// UseImageHosts indicates that /etc/hosts should not be managed by Podman, and instead sourced from the image. Conflicts with HostAdd.
	UseImageHosts bool `json:"use_image_hosts,omitempty"`
	// UseImageResolvConf indicates that resolv.conf should not be managed by Podman, but instead sourced from the image. Conflicts with DNSServer, DNSSearch, DNSOption.
	UseImageResolveConf bool `json:"use_image_resolve_conf,omitempty"`
	// User is the user the container will be run as. Can be given as a UID or a username; if a username, it will be resolved within the container, using the container's /etc/passwd. If unset, the container will be run as root. Optional.
	User string `json:"user,omitempty"`
	Userns *Namespace `json:"userns,omitempty"`
	Utsns *Namespace `json:"utsns,omitempty"`
	// Volumes are named volumes that will be added to the container. These will supersede Image Volumes and VolumesFrom volumes where there are conflicts. Optional.
	Volumes []NamedVolume `json:"volumes,omitempty"`
	// VolumesFrom is a set of containers whose volumes will be added to this container. The name or ID of the container must be provided, and may optionally be followed by a : and then one or more comma-separated options. Valid options are 'ro', 'rw', and 'z'. Options will be used for all volumes sourced from the container.
	VolumesFrom []string `json:"volumes_from,omitempty"`
	// Weight per cgroup per device, can override BlkioWeight
	WeightDevice map[string]LinuxWeightDevice `json:"weightDevice,omitempty"`
	// WorkDir is the container's working directory. If unset, the default, /, will be used. Optional.
	WorkDir string `json:"work_dir,omitempty"`
}
